/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is checked in here so
// the isolated visualization can typecheck before being copied into a site.
